// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxwdqmuyjlfpcxtlsare.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4d2RxbXV5amxmcGN4dGxzYXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MzYyMDQsImV4cCI6MjA1NzExMjIwNH0.5eVRYrfJwa8Q35f-OrbC2Ci0ND1Fom6Fl-uoz5dEHKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);